apiVersion: v1
kind: Service
metadata:
  # namespace: eshoponweb-user009
  name: eshoponweb
  namespace: eshopweb-user009
  labels:
    app: eshoponweb
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: eshoponweb-app
